import React from 'react';
import {Box, Container, Flex, Text, useColorModeValue} from '@chakra-ui/react';
import Head from 'next/head';
import {Metadata} from "next";

export const metadata: Metadata = {
    title: 'Login Page',
    description: 'Generated by create next app',
}

const AuthLayout = ({children}: { children: React.ReactNode }) => {

    return (
        <>
            <Head>
                <title>Auth</title>
                <meta name="description" content="Generated by create next app"/>
                <meta charSet="UTF-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            </Head>
            <Container bg={'#f0e6d6'} color={'#5c5346'} width={"100%"} maxW="100%" minH="100vh" display="flex"
                       flexDirection="column"
                       justifyContent="center"
                       alignItems="center">
                <Flex direction="column" align="center" mt={-20} pb={10}>
                    <Box className="logo" mb="10px">
                        <img src="/images/logo.jpg" alt="Logo" style={{width: '100px'}}/>
                    </Box>
                    <Text fontSize="2xl" fontWeight="bold" fontFamily={"JetBrains Mono"} letterSpacing={2}>
                        ЧашкаКофе
                    </Text>
                </Flex>
                {children}
            </Container>
        </>
    );
};

export default AuthLayout;
