'use client'
import Header from "@/components/header";
import ReservationForm from "@/components/reservationForm";
import InteractiveTableMap from "@/components/tableMap";
import { API_URL } from "@/utils/constants";
import { Button, Select, VStack, Text, Box, Flex } from "@chakra-ui/react";
import axios from "axios";
import { Metadata } from "next";
import { useEffect, useState } from "react";

const metadata: Metadata = {
    title: 'Reservation Page',
    description: 'Generated by create next app',
  }

interface ITable {
    number: string;
    seats: number;
    is_available: boolean;
}


const ReservationPage: React.FC = () => {
    const [tables, setTables] = useState<ITable[]>([]);

    useEffect(() => {
        const fetchTables = async () => {
            try {
            const response = await axios.get(`${API_URL}/v1/table/all`, {
                headers: {
                    'Content-Type': 'application/json',
                },
                withCredentials: true
            });
            if(response.status === 200 && response.data) {
                setTables(response.data.data);
            }
        } catch (error) {
            window.location.href='/login';
        }
        }
        fetchTables();
    },[]);

    if(tables?.length > 0) {
        return (
            <>
            <Header isAuth={true}/>
            <Flex padding="4" alignItems="center" justifyContent="center" className="bg-coffee-light">
                <Box flex="2" margin="4" className="rounded-lg shadow-lg bg-white">
                    <InteractiveTableMap tables={tables} />
                </Box>
            </Flex>
            </>
        )
    } else {
        return (
            <>
            <Header isAuth={true}/>
            <Flex padding="4" alignItems="center" justifyContent="center" className="bg-coffee-light">
                Извините, но на данный момент столов нет
            </Flex>
            </>
        )
    }

    

    
}

export default ReservationPage;